name: Automated AI-SEO Blog

on:
  schedule:
   - cron: "0 16 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ai-seo-blog
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NEWS_FEEDS_GENERAL: ${{ vars.NEWS_FEEDS_GENERAL }}
      NEWS_FEEDS_QUERY: ${{ vars.NEWS_FEEDS_QUERY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install openai feedparser beautifulsoup4

      - name: Generate post(s)
        run: |
          python generate.py --auto
          python rebuild_index.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "auto: generate posts & rebuild index" || echo "No changes"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
